feishu:
  app_id: "cli_a936a9e2a6215bd3"
  app_secret: "J6wEYJa5JO9LvStQoLlhgd01Dhvwk1Ul"
  verification_token: "gYpg5YW9AXVAue1WoGcUfbDKuTod32Gn"
  encrypt_key: ""
  allow_from: []

server:
  bind_host: "0.0.0.0"
  bind_port: 18789

gitlab:
  base_url: "http://60.16.4.220:30080"
  access_token: "glpat-JQ2tGwB7WCXJdBFW39Ses286MQp1OjMH.01.0w0o8yq5l"

projects:
  - name: "运维项目"
    environments: ["test", "prod"]
    repos:
      - name: "gitlabci-configs"
        repo: "devops/gitlabci-configs"
        id: 9
  - name: "全飞云演示项目"
    environments: ["test", "prod"]
    repos:
      - name: "前端仓库"
        repo: "qfy_workgroup/qfy-ui"
        id: 11
      - name: "后端仓库"
        repo: "qfy_workgroup/qfy-cloud"
        id: 10
